### ISSUE TITLE
When task from setup file cannot be read

### ISSUE THREAD

**Issue by jandery** [Schinzel/atexpose#1]
A task could not be set up when reading imported setup file. I'd like an email to be sent when this fails.

**Comment by Schinzel** [comment]
Added a second optional argument: 
String loadScriptFile(String FileName, [AlphNumString Recipient])

Can also be used from Java
        atExpose.loadScriptFile("sample_script_file/scriptfile.txt");

If an error occurs when executing one of the commands in the script file an error log entry is sent to the argument address. Requires an SMTP to be set up before using loadScriptFile. 

If this is acceptable I will deploy a new version

**Comment by Schinzel** [comment]
Fixed
